import { IconTheme } from '@/domain/icon/IconTheme';
import { AppLanguage } from '@/domain/localization/AppLanguage';
import type {
  Activity,
  AppIconPreferences,
  Course,
  EvaluationActivity,
  EventActivity,
  GradePlannerDataModel,
  NotificationSettings,
  Semester,
  StudyActivity,
  UC,
  UserProfile,
} from '@/domain/grade-planner/schema';
import {
  calculateCourseStats,
  calculateSemesterStats,
  calculateUcStats,
  getUpcomingDeadlines,
} from '@/domain/grade-planner/utils';

const now = new Date();

const isoAt = (offsetDays: number, hour = 10, minute = 0): string => {
  const date = new Date(now);
  date.setDate(date.getDate() + offsetDays);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

const isoDateAt = (offsetDays: number): string => isoAt(offsetDays, 12, 0).slice(0, 10);

const reminders = [10080, 1440, 180];

const userProfile: UserProfile = {
  id: 'user-001',
  displayName: 'Renan Botasse',
  email: 'renan.botasse@uab.pt',
  language: AppLanguage.PT_PT,
  timezone: 'Europe/Lisbon',
  defaultGradeScale: '0-20',
  defaultMinimumPassingGrade: 10,
  themeMode: 'light',
};

const notificationSettings: NotificationSettings = {
  enabled: true,
  timezone: 'Europe/Lisbon',
  reminderMinutes: reminders,
  dailyDigestHour: 8,
};

const appIconPreferences: AppIconPreferences = {
  selectedVariant: IconTheme.DARK_PURPLE,
  availableVariants: [
    IconTheme.DARK_PURPLE,
    IconTheme.LIGHT_PURPLE,
    IconTheme.MONOCHROME,
    IconTheme.GREEN,
  ],
  applyToLauncherIcon: true,
};

const courses: Course[] = [
  {
    id: 'course-lei-uab',
    userId: userProfile.id,
    code: 'LEI-UAb',
    name: 'Licenciatura em Engenharia Informatica',
    institution: 'Universidade Aberta',
    gradeScale: '0-20',
    minimumPassingGrade: 10,
    startDate: isoDateAt(-620),
    expectedEndDate: isoDateAt(460),
    active: true,
  },
];

const semesters: Semester[] = [
  {
    id: 'semester-2025-2',
    courseId: 'course-lei-uab',
    title: '2o Semestre - 2o Ano',
    yearLabel: '2025/2026',
    dateRange: {
      startDate: isoDateAt(-320),
      endDate: isoDateAt(-170),
    },
    status: 'passado',
    notes: 'Semestre concluido com bom desempenho em programacao e web.',
  },
  {
    id: 'semester-2026-1',
    courseId: 'course-lei-uab',
    title: '1o Semestre - 3o Ano',
    yearLabel: '2026/2027',
    dateRange: {
      startDate: isoDateAt(-45),
      endDate: isoDateAt(110),
    },
    status: 'atual',
    notes: 'Foco em bases de dados, redes e engenharia de software.',
  },
];

const ucs: UC[] = [
  {
    id: 'uc-prog-web',
    courseId: 'course-lei-uab',
    semesterId: 'semester-2025-2',
    code: 'UCPW',
    name: 'Programacao Web',
    ects: 6,
    teachers: ['Rita Cardoso'],
    notes: 'UC concluida com projeto final acima da media.',
    assessmentSystem: {
      gradeScale: '0-20',
      minimumPassingGrade: 10,
      inheritedFromCourse: true,
    },
  },
  {
    id: 'uc-matematica-discreta',
    courseId: 'course-lei-uab',
    semesterId: 'semester-2025-2',
    code: 'UCMD',
    name: 'Matematica Discreta',
    ects: 8,
    teachers: ['Miguel Rocha'],
    notes: null,
    assessmentSystem: {
      gradeScale: '0-20',
      minimumPassingGrade: 10,
      inheritedFromCourse: true,
    },
  },
  {
    id: 'uc-programacao-avancada',
    courseId: 'course-lei-uab',
    semesterId: 'semester-2025-2',
    code: 'UCPA',
    name: 'Programacao Avancada',
    ects: 6,
    teachers: ['Luis Almeida'],
    notes: null,
    assessmentSystem: {
      gradeScale: '0-20',
      minimumPassingGrade: 10,
      inheritedFromCourse: true,
    },
  },
  {
    id: 'uc-analise-sistemas',
    courseId: 'course-lei-uab',
    semesterId: 'semester-2026-1',
    code: 'UCAS',
    name: 'Analise e Desenho de Sistemas',
    ects: 6,
    teachers: ['Joana Martins'],
    notes: 'Projeto final com entrega em duas fases.',
    assessmentSystem: {
      gradeScale: '0-20',
      minimumPassingGrade: 10,
      inheritedFromCourse: true,
    },
  },
  {
    id: 'uc-bases-dados',
    courseId: 'course-lei-uab',
    semesterId: 'semester-2026-1',
    code: 'UCBD',
    name: 'Bases de Dados',
    ects: 8,
    teachers: ['Carlos Freitas'],
    notes: null,
    assessmentSystem: {
      gradeScale: '0-20',
      minimumPassingGrade: 10,
      inheritedFromCourse: true,
    },
  },
  {
    id: 'uc-eng-software',
    courseId: 'course-lei-uab',
    semesterId: 'semester-2026-1',
    code: 'UCES',
    name: 'Engenharia de Software',
    ects: 6,
    teachers: ['Helena Nunes'],
    notes: 'Avaliacao continua com revisoes de sprint.',
    assessmentSystem: {
      gradeScale: '0-20',
      minimumPassingGrade: 10,
      inheritedFromCourse: true,
    },
  },
  {
    id: 'uc-redes',
    courseId: 'course-lei-uab',
    semesterId: 'semester-2026-1',
    code: 'UCRD',
    name: 'Redes de Computadores',
    ects: 4,
    teachers: ['Patricia Silva'],
    notes: null,
    assessmentSystem: {
      gradeScale: '0-20',
      minimumPassingGrade: 10,
      inheritedFromCourse: true,
    },
  },
];

const evaluation = (
  input: Omit<EvaluationActivity, 'type' | 'createdAt' | 'updatedAt' | 'dueAt'> & {
    dueOffsetDays: number;
  },
): EvaluationActivity => ({
  ...input,
  type: 'evaluation',
  dueAt: isoAt(input.dueOffsetDays, 10, 0),
  createdAt: isoAt(input.dueOffsetDays - 35, 11, 0),
  updatedAt: isoAt(Math.min(input.dueOffsetDays - 1, -1), 18, 0),
});

const studyTask = (
  input: Omit<StudyActivity, 'type' | 'createdAt' | 'updatedAt' | 'dueAt'> & {
    dueOffsetDays: number;
  },
): StudyActivity => ({
  ...input,
  type: 'study_task',
  dueAt: isoAt(input.dueOffsetDays, 19, 0),
  createdAt: isoAt(input.dueOffsetDays - 7, 9, 0),
  updatedAt: isoAt(Math.min(input.dueOffsetDays - 1, -1), 21, 0),
});

const eventItem = (
  input: Omit<EventActivity, 'type' | 'createdAt' | 'updatedAt' | 'dueAt'> & {
    dueOffsetDays: number;
  },
): EventActivity => ({
  ...input,
  type: 'event',
  dueAt: isoAt(input.dueOffsetDays, 18, 30),
  createdAt: isoAt(input.dueOffsetDays - 21, 10, 30),
  updatedAt: isoAt(Math.min(input.dueOffsetDays - 2, -1), 12, 0),
});

const activities: Activity[] = [
  // Past semester evaluations
  evaluation({
    id: 'ev-web-1',
    title: 'Mini projeto frontend',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-prog-web',
    canAffectGrade: true,
    grade: { score: { value: 15, scale: '0-20' }, weight: { percentage: 25 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'project',
    dueOffsetDays: -290,
  }),
  evaluation({
    id: 'ev-web-2',
    title: 'Teste de APIs REST',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-prog-web',
    canAffectGrade: true,
    grade: { score: { value: 17, scale: '0-20' }, weight: { percentage: 25 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'exam',
    dueOffsetDays: -270,
  }),
  evaluation({
    id: 'ev-web-3',
    title: 'Projeto final full-stack',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-prog-web',
    canAffectGrade: true,
    grade: { score: { value: 16, scale: '0-20' }, weight: { percentage: 50 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'project',
    dueOffsetDays: -242,
  }),
  evaluation({
    id: 'ev-md-1',
    title: 'Ficha de exercicios',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-matematica-discreta',
    canAffectGrade: true,
    grade: { score: { value: 13, scale: '0-20' }, weight: { percentage: 20 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'assignment',
    dueOffsetDays: -286,
  }),
  evaluation({
    id: 'ev-md-2',
    title: 'Teste intermedio',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-matematica-discreta',
    canAffectGrade: true,
    grade: { score: { value: 14, scale: '0-20' }, weight: { percentage: 30 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'exam',
    dueOffsetDays: -266,
  }),
  evaluation({
    id: 'ev-md-3',
    title: 'Exame final',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-matematica-discreta',
    canAffectGrade: true,
    grade: { score: { value: 16, scale: '0-20' }, weight: { percentage: 50 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'exam',
    dueOffsetDays: -244,
  }),
  evaluation({
    id: 'ev-pa-1',
    title: 'Kata de algoritmos',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-programacao-avancada',
    canAffectGrade: true,
    grade: { score: { value: 16, scale: '0-20' }, weight: { percentage: 30 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'assignment',
    dueOffsetDays: -282,
  }),
  evaluation({
    id: 'ev-pa-2',
    title: 'Projeto concorrencia',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-programacao-avancada',
    canAffectGrade: true,
    grade: { score: { value: 15, scale: '0-20' }, weight: { percentage: 30 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'project',
    dueOffsetDays: -258,
  }),
  evaluation({
    id: 'ev-pa-3',
    title: 'Prova pratica',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: 'uc-programacao-avancada',
    canAffectGrade: true,
    grade: { score: { value: 17, scale: '0-20' }, weight: { percentage: 40 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'lab',
    dueOffsetDays: -238,
  }),

  // Current semester UC evaluations (weights sum 100 in each UC)
  evaluation({
    id: 'ev-ads-1',
    title: 'Quiz de requisitos',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-analise-sistemas',
    canAffectGrade: true,
    grade: { score: { value: 14, scale: '0-20' }, weight: { percentage: 10 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'quiz',
    dueOffsetDays: -28,
  }),
  evaluation({
    id: 'ev-ads-2',
    title: 'Trabalho de modelacao UML',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-analise-sistemas',
    canAffectGrade: true,
    grade: { score: { value: 16, scale: '0-20' }, weight: { percentage: 30 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'assignment',
    dueOffsetDays: -12,
  }),
  evaluation({
    id: 'ev-ads-3',
    title: 'Projeto final de analise',
    description: 'Entrega principal com backlog e diagramas.',
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-analise-sistemas',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 40 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'project',
    dueOffsetDays: 8,
  }),
  evaluation({
    id: 'ev-ads-4',
    title: 'Apresentacao oral do projeto',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-analise-sistemas',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 20 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'participation',
    dueOffsetDays: 24,
  }),

  evaluation({
    id: 'ev-bd-1',
    title: 'Teste SQL',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-bases-dados',
    canAffectGrade: true,
    grade: { score: { value: 13, scale: '0-20' }, weight: { percentage: 25 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'exam',
    dueOffsetDays: -21,
  }),
  evaluation({
    id: 'ev-bd-2',
    title: 'Laboratorio de indexacao',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-bases-dados',
    canAffectGrade: true,
    grade: { score: { value: 17, scale: '0-20' }, weight: { percentage: 25 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'lab',
    dueOffsetDays: -6,
  }),
  evaluation({
    id: 'ev-bd-3',
    title: 'Projeto de modelacao fisica',
    description: 'Modelo relacional + scripts de migracao.',
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-bases-dados',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 30 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'project',
    dueOffsetDays: 3,
  }),
  evaluation({
    id: 'ev-bd-4',
    title: 'Exame final de base de dados',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-bases-dados',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 20 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'exam',
    dueOffsetDays: 26,
  }),

  evaluation({
    id: 'ev-es-1',
    title: 'Sprint review 1',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-eng-software',
    canAffectGrade: true,
    grade: { score: { value: 15, scale: '0-20' }, weight: { percentage: 20 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'participation',
    dueOffsetDays: -19,
  }),
  evaluation({
    id: 'ev-es-2',
    title: 'Sprint review 2',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-eng-software',
    canAffectGrade: true,
    grade: { score: { value: 14, scale: '0-20' }, weight: { percentage: 20 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'participation',
    dueOffsetDays: -4,
  }),
  evaluation({
    id: 'ev-es-3',
    title: 'Entrega do backlog refinado',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-eng-software',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 25 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'assignment',
    dueOffsetDays: 1,
  }),
  evaluation({
    id: 'ev-es-4',
    title: 'Projeto final da disciplina',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-eng-software',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 35 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'project',
    dueOffsetDays: 16,
  }),

  evaluation({
    id: 'ev-rd-1',
    title: 'Ficha de subnetting',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-redes',
    canAffectGrade: true,
    grade: { score: { value: 12, scale: '0-20' }, weight: { percentage: 15 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'assignment',
    dueOffsetDays: -14,
  }),
  evaluation({
    id: 'ev-rd-2',
    title: 'Laboratorio Packet Tracer',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-redes',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 35 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'lab',
    dueOffsetDays: 4,
  }),
  evaluation({
    id: 'ev-rd-3',
    title: 'Prova teorica',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-redes',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 30 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'exam',
    dueOffsetDays: 13,
  }),
  evaluation({
    id: 'ev-rd-4',
    title: 'Prova pratica de routing',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-redes',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 20 }, pointsPossible: 20 },
    reminders,
    evaluationCategory: 'exam',
    dueOffsetDays: 31,
  }),

  // Study tasks
  studyTask({
    id: 'task-ads-revisao',
    title: 'Revisao de requisitos e casos de uso',
    description: 'Checklist para reduzir retrabalho do projeto final.',
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-analise-sistemas',
    canAffectGrade: false,
    grade: null,
    reminders: [1440, 180],
    objective: 'Preparar entrega do projeto de analise',
    dueOffsetDays: 2,
  }),
  studyTask({
    id: 'task-bd-sql',
    title: 'Maratona SQL e normalizacao',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: 'uc-bases-dados',
    canAffectGrade: false,
    grade: null,
    reminders: [1440],
    objective: 'Treinar joins e otimizacao para o projeto BD',
    dueOffsetDays: 6,
  }),
  studyTask({
    id: 'task-redes-pratica',
    title: 'Pratica guiada de VLAN e OSPF',
    description: 'Atividade com ponto extra para participacao.',
    status: 'in_progress',
    semesterId: 'semester-2026-1',
    ucId: 'uc-redes',
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 5 }, pointsPossible: 20 },
    reminders: [1440, 180],
    objective: 'Consolidar configuracao de routing dinâmico',
    dueOffsetDays: 5,
  }),
  studyTask({
    id: 'task-es-resumo',
    title: 'Resumo de historias de utilizador',
    description: null,
    status: 'completed',
    semesterId: 'semester-2026-1',
    ucId: 'uc-eng-software',
    canAffectGrade: false,
    grade: null,
    reminders: [180],
    objective: 'Preparar refinamento da sprint review',
    dueOffsetDays: -2,
  }),

  // Independent events (outside UC)
  eventItem({
    id: 'event-job-fair',
    title: 'Job Fair de Tecnologia UAb',
    description: 'Participacao voluntaria com certificado.',
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: null,
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 5 }, pointsPossible: 20 },
    reminders: [10080, 1440],
    location: 'Lisboa - Polo UAb',
    dueOffsetDays: 5,
  }),
  eventItem({
    id: 'event-tech-talk',
    title: 'Tech Talk: IA aplicada a educacao',
    description: null,
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: null,
    canAffectGrade: false,
    grade: null,
    reminders: [1440],
    location: 'Online',
    dueOffsetDays: 12,
  }),
  eventItem({
    id: 'event-hackathon',
    title: 'Hackathon Academico',
    description: 'Evento de 24h com avaliacao por jurados.',
    status: 'planned',
    semesterId: 'semester-2026-1',
    ucId: null,
    canAffectGrade: true,
    grade: { score: null, weight: { percentage: 10 }, pointsPossible: 20 },
    reminders: [10080, 1440],
    location: 'Porto',
    dueOffsetDays: 58,
  }),
  eventItem({
    id: 'event-career-past',
    title: 'Seminario de carreira',
    description: null,
    status: 'completed',
    semesterId: 'semester-2025-2',
    ucId: null,
    canAffectGrade: true,
    grade: { score: { value: 18, scale: '0-20' }, weight: { percentage: 5 }, pointsPossible: 20 },
    reminders: [1440],
    location: 'Online',
    dueOffsetDays: -180,
  }),
];

export const gradePlannerMockData: GradePlannerDataModel = {
  generatedAt: now.toISOString(),
  userProfile,
  notificationSettings,
  appIconPreferences,
  courses,
  semesters,
  ucs,
  activities,
};

const activeCourse = courses[0];
const currentSemester = semesters.find((semester) => semester.status === 'atual');

export const gradePlannerMockDerived = {
  ucStats: ucs.reduce<Record<string, ReturnType<typeof calculateUcStats>>>((acc, uc) => {
    acc[uc.id] = calculateUcStats(uc, activities);
    return acc;
  }, {}),
  semesterStats: semesters.reduce<Record<string, ReturnType<typeof calculateSemesterStats>>>((acc, semester) => {
    acc[semester.id] = calculateSemesterStats(semester, ucs, activities);
    return acc;
  }, {}),
  courseStats: calculateCourseStats(activeCourse, semesters, ucs, activities),
  upcomingDeadlines7Days: getUpcomingDeadlines(activities, 7),
  currentSemesterId: currentSemester?.id ?? null,
};
