export const queryKeys = {
  profile: ['profile'] as const,
  mockDataMode: ['settings', 'mockDataMode'] as const,
  cursos: ['cursos'] as const,
  activeCurso: ['activeCurso'] as const,
  semesters: (cursoId?: number) => ['semesters', cursoId ?? 'all'] as const,
  semester: (semesterId: number) => ['semester', semesterId] as const,
  semesterInsights: (semesterId: number) => ['semesters', 'insights', semesterId] as const,
  ucs: (semesterId: number) => ['ucs', semesterId] as const,
  uc: (ucId: number) => ['uc', ucId] as const,
  avaliacoes: (ucId: number) => ['uc', ucId, 'avaliacoes'] as const,
  ucStatus: (ucId: number) => ['uc', ucId, 'status'] as const,
  eventsInRange: (startISO: string, endISO: string) => ['events', startISO, endISO] as const,
  eventsByDate: (dateISO: string) => ['events', 'date', dateISO] as const,
  calendarData: (month: string) => ['calendar', month] as const,
  activities: ['activities'] as const,
  upcomingAvaliacoes: ['activities', 'upcoming'] as const,
  pendingAvaliacoes: ['activities', 'pending'] as const,
  todayAvaliacoes: ['activities', 'today'] as const,
  upcomingDeadlines: ['activities', 'deadlines', 'upcoming'] as const,
  todayDeadlines: ['activities', 'deadlines', 'today'] as const,
  dashboard: (cursoId?: number) => ['dashboard', cursoId ?? 'active'] as const,
  progress: (cursoId?: number) => ['progress', cursoId ?? 'global'] as const,
} as const;
